# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/    
    steps:
    - name: Hello world action
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.test }}
        
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      
    - run: echo $GITHUB_SERVER_URL
    - run: echo $GITHUB_REPOSITORY
    - run: ./.github/scripts/decrypt_secret.sh
    - name: Test printing your secret (Remove this step in production)
      run: cat $HOME/secrets/my_secret.json
